<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>movie_reservation_system</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.21" />
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Security" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dto\" />
    <Folder Include="Exception\" />
    <Folder Include="Exception\Auth\" />
    <Folder Include="Exception\Movies\" />
    <Folder Include="Exception\Showtime\" />
    <Folder Include="Extension\" />
    <Folder Include="Features\Auth\" />
    <Folder Include="Features\Auth\UserLogin\" />
    <Folder Include="Features\Auth\UserRegister\" />
    <Folder Include="Features\Movies\" />
    <Folder Include="Features\Movies\AddMovies\" />
    <Folder Include="Features\Movies\DeleteMovies\" />
    <Folder Include="Features\Movies\UpdateMovies\" />
    <Folder Include="Features\Showtime\" />
    <Folder Include="Features\Showtime\AddShowtime\" />
    <Folder Include="Features\Showtime\ListShowtime\" />
    <Folder Include="Features\Showtime\Specifications\" />
    <Folder Include="Features\Showtime\UpdateShowtime\" />
    <Folder Include="Infrastructure\" />
    <Folder Include="Model\" />
  </ItemGroup>

</Project>
